# Generated by Django 2.1.7 on 2019-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTerrorism',
            fields=[
                ('iyear', models.BigIntegerField(blank=True, null=True)),
                ('imonth', models.BigIntegerField(blank=True, null=True)),
                ('iday', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('country_txt', models.TextField(blank=True, null=True)),
                ('region_txt', models.TextField(blank=True, null=True)),
                ('provstate', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('multiple', models.BigIntegerField(blank=True, null=True)),
                ('success', models.BigIntegerField(blank=True, null=True)),
                ('suicide', models.BigIntegerField(blank=True, null=True)),
                ('attacktype1_txt', models.TextField(blank=True, null=True)),
                ('attacktype2_txt', models.TextField(blank=True, null=True)),
                ('attacktype3_txt', models.TextField(blank=True, null=True)),
                ('targtype1_txt', models.TextField(blank=True, null=True)),
                ('targsubtype1_txt', models.TextField(blank=True, null=True)),
                ('corp1', models.TextField(blank=True, null=True)),
                ('natlty1_txt', models.TextField(blank=True, null=True)),
                ('gname', models.TextField(blank=True, null=True)),
                ('claimmode_txt', models.TextField(blank=True, null=True)),
                ('weaptype1_txt', models.TextField(blank=True, null=True)),
                ('weapsubtype1_txt', models.TextField(blank=True, null=True)),
                ('weaptype2_txt', models.TextField(blank=True, null=True)),
                ('weapsubtype2_txt', models.TextField(blank=True, null=True)),
                ('kidhijcountry', models.TextField(blank=True, null=True)),
                ('ransom', models.FloatField(blank=True, null=True)),
                ('nkill', models.FloatField(blank=True, null=True)),
                ('nwound', models.FloatField(blank=True, null=True)),
                ('index1', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'global_terrorism',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorldHappinessIndex',
            fields=[
                ('country', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('life_ladder', models.FloatField(blank=True, null=True)),
                ('index1', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'world_happiness_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worldnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('number_of_comments', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worldnews',
                'managed': False,
            },
        ),
    ]
